### PR TITLE
remove unicode_compat_util

### LINKED ISSUE #30: remove support of Erlang OTP versions < 21
remove unicode_compat dependency and only build for OTP 21 and 22.

### PR DESCRIPTION
**Pull request by benoitc**
with this version we are only  compatible with erlang 21.x and 22.x.
This reduce the disk usage and ease the portability

fix #30

### CODE REVIEW

**Comment by olleolleolle** [comment]
@benoitc Would this change be possible to consider, or is it "an idea"?

**Comment by benoitc** [comment]
this is a planed change. i will do it after next 1.x version of hackney. Just took more time than expected. wWhy the question?

**Comment by olleolleolle** [comment]
Oh, I was merely curious, no good reason!

**Comment by benoitc** [comment]
closing unicode_util_compat dependency has been removed in master. 7.0.0 will be released later this month.

**Pull request closed without merging**
