### PR TITLE
Update to support IDNA 13

### PR DESCRIPTION
**Pull request by ruudk**
It seems that Travis it not automatically building this PR. How to know if it's Ok?

### CODE REVIEW

**Comment by ruudk** [comment]
Added a test for the emoji conversion but it still fails, I don't understand:
```

  1) compat_test:emoji_test/0
     Failure/Error: {exit,
                        {bad_label,
                            {context,
                                "Codepoint 128065 not allowed ('DISALLOWED') at position 0 in [128065,128068,\n                                                              128065]"}},
                        [{idna,check_context,4,
                             [{file,
                                  "/Users/Ruud/Downloads/erlang-idna/src/idna.erl"},
                              {line,209}]},
                         {idna,check_label,4,
                             [{file,
                                  "/Users/Ruud/Downloads/erlang-idna/src/idna.erl"},
                              {line,254}]},
                         {idna,alabel,1,
                             [{file,
                                  "/Users/Ruud/Downloads/erlang-idna/src/idna.erl"},
                              {line,283}]},
                         {idna,encode_1,2,
                             [{file,
                                  "/Users/Ruud/Downloads/erlang-idna/src/idna.erl"},
                              {line,145}]},
                         {compat_test,'-emoji_test/0-fun-0-',0,
                             [{file,
                                  "/Users/Ruud/Downloads/erlang-idna/test/compat_test.erl"},
                              {line,22}]},
                         {eunit_test,'-mf_wrapper/2-fun-0-',2,
                             [{file,"eunit_test.erl"},{line,273}]},
                         {eunit_test,run_testfun,1,
                             [{file,"eunit_test.erl"},{line,71}]},
                         {eunit_proc,run_test,1,
                             [{file,"eunit_proc.erl"},{line,522}]}]}
     Output:

```

**Comment by benoitc** [comment]
Thanks for the PR!

After checking it, i believe the test doesn't pass because it's not valid for IDNA2008:
https://util.unicode.org/UnicodeJsps/idna.jsp?a=👁👄👁.fm

or: 
https://util.unicode.org/UnicodeJsps/character.jsp?a=👁&B1=Show

not what to do, after all the lib is about validating against IDNA2003 and IDNA2008 :) 

Maybe adding another option would work but unsure if we should do it. I would like to merge your changes for the version 13. Can you split your PR in 2 so we can handle the emoji issue separately?

**Comment by ruudk** [comment]
Just found out the same thing. TIL! 

Updated the PR :)

**Comment by ruudk** [comment]
I see what I did now, this works:
```
test2() ->
  ?assertEqual("xn--mp8hai.fm", idna:encode("👁👄👁.fm", [uts46])).
test23() ->
  ?assertEqual("👁👄👁.fm", idna:decode("xn--mp8hai.fm", [uts46])).
```

**Comment by benoitc** [comment]
merged in latest master. Thanks!

**Pull request closed without merging**
